export const ItemTypes = {
  BODY: 'BODY',
  CARD: 'CARD',
  COMPONENT: 'COMPONENT',
  HEADING1: 'HEADING1',
  HEADING2: 'HEADING2',
  HEADING3: 'HEADING3',
  HEADING4: 'HEADING4',
  HEADING5: 'HEADING5',
  HEADING6: 'HEADING6',
};
